name: Publish To Heroku With Docker
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: cpplox
    steps:
      - name: Checkout Dir
        uses: actions/checkout@v2
      - name: Heroku Deployment
        uses: ElayGelbart/Heroku-Auto-Deployment@v1.0.6
        with:
          herokuApiKey: ${{ secrets.HEROKU_API_KEY}}
          herokuAppName: cpplox
          useDocker: true
